export enum EventConditionType {
  LOGIN_BETWEEN = 'LOGIN_BETWEEN',
  LOGIN_CONSECUTIVE_DAYS = 'LOGIN_CONSECUTIVE_DAYS',
  USER_INVITE = 'USER_INVITE',
  QUEST_CLEAR_SPECIFIC = 'QUEST_CLEAR_SPECIFIC',
  QUEST_CLEAR_COUNT = 'QUEST_CLEAR_COUNT',
}
