export enum RewardRequestStatusType {
  NONE = 'NONE',
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

// REQUESTED -> REJECTED
// REQUESTED -> CANCELLED
// REQUESTED -> APPROVED -> CANCELLED
// REQUESTED -> APPROVED -> PROCESSING -> FAILED
// REQUESTED -> APPROVED -> PROCESSING -> DONE
