// Error codes
export const ERROR_CODE_INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const ERROR_CODE_BAD_REQUEST = 'BAD_REQUEST';
export const ERROR_CODE_UNAUTHORIZED = 'UNAUTHORIZED';
export const ERROR_CODE_FORBIDDEN = 'FORBIDDEN';
export const ERROR_CODE_NOT_FOUND = 'NOT_FOUND';
export const ERROR_CODE_CONFLICT = 'CONFLICT';
